[package]
name = "tbios"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-bindings = "0.8.1"
nix = { version = "0.28.0", features = ["fs"] }
